### PR TITLE
Apply PHP 7.4 syntax and typed property

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Since composer.json require php 7.4, php 7.4 syntax can be applied with typed properties. 

- For `final class`, typed properties for protected is allowed if no inherit of parent or used by its final class parent.
- Otherwise, update only private properties.

### CODE REVIEW

**Comment by samsonasik** [comment]
PHPUnit error is unrelated:

```bash
Running ./vendor/bin/phpunit
PHP Fatal error:  Declaration of Laminas\ServiceManager\AbstractTypedContainerImplementation::has(string $id): bool must be compatible with Laminas\Feed\Reader\ExtensionManagerInterface::has($extension) in /github/workspace/src/Reader/ExtensionPluginManager.php on line 28
```

ref https://github.com/laminas/laminas-feed/pull/57#issuecomment-1188747233

**Comment by Ocramius** [comment]
@samsonasik please check https://github.com/laminas/laminas-feed/pull/59 - if reviewed, I can release and then merge this one on top of it.

**Comment by Ocramius** [comment]
@samsonasik a rebase should make this green

**Comment by samsonasik** [comment]
@Ocramius rebased.

**Review by Ocramius — APPROVED** [review]
LGTM :+1:

**Pull request merged**
