### PR TITLE
Remove support for PHP 8.0, Remove hard dependency on service manager

### PR DESCRIPTION
**Pull request by gsteel**
Further to discussion in #75, removing the hard-dependency on laminas/service-manager here allows consumers to use the component in projects that require `psr/container:2`, providing they only use the `StandaloneExtensionManager` for `Reader\` and `Writer\`

### CODE REVIEW

**Comment by gsteel** [comment]
Ughh - we have to drop PHP 8.0 and work around the BC break in tests introduced in SM 3.21

**Comment by froschdesign** [comment]
@gsteel 
Thanks for the quick solution! 👍🏻 

@MegaChriz
Can you check this?

**Comment by MegaChriz** [comment]
Thanks for picking this up so quickly! On my local install I have PHP 8.1 and that looked to go well. I saw that on a `composer update` on a Drupal 10 install that laminas/laminas-servicemanager got removed. Unit and Kernel tests for Feeds still passed. The Functional tests I did not run yet, as they take more time to run on my local machine.

I hope to test with PHP 8.2 soon!

**Comment by MegaChriz** [comment]
Feeds does indeed use `\Laminas\Feed\Reader\StandaloneExtensionManager`.

These are other classes/interfaces that Feeds uses:
- Laminas\Feed\Reader\Exception\ExceptionInterface
- Laminas\Feed\Reader\ExtensionManagerInterface
- Laminas\Feed\Reader\Reader
- Laminas\Feed\Reader\Extension\AbstractEntry
- Laminas\Feed\Reader\FeedSet

**Comment by gsteel** [comment]
This just needs an approving review from someone on the @laminas/technical-steering-committee and it can be released

**Comment by MegaChriz** [comment]
**Feeds tests pass**
I ran all Feeds tests locally now on PHP 8.2.8 and all that are at least related to parsing RSS Feeds passed!

**Feeds can now be installed using composer**
I also tested if I could install drupal/feeds on PHP 8.2.8 now by using the following definitions in composer.json of a local project:
```
"repositories": [
   (...)
   {
        "type": "vcs",
        "url": "https://github.com/gsteel/laminas-feed.git"
    }
],
```
```
"require": {
   (...)
    "laminas/laminas-feed": "dev-remove-hard-dependency-on-service-manager as 2.13"
},
```

With that I could require drupal/feeds with success!
(And without the changes from this issue composer reports that the requirements could not be resolved.)

**Review by froschdesign — APPROVED** [review]

**Review by Ocramius — APPROVED** [review]
LGTM, thanks @gsteel!

**Pull request merged**
